#include "asteroid.h"
#include <cstdlib>
#include <cmath>

asteroid::asteroid(AsteroidSize size) : size(size) {
    InitBySize();
    position = RandomEdgeSpawn();

    // Random direction toward center
    float angle = ((rand() % 360) * M_PI / 180.0f);
    float speed = 50.0f + rand() % 100;
    velocity.setX(cos(angle) * speed);
    velocity.setY(sin(angle) * speed);

    rotationSpeed = 20.0f + rand() % 60;
}
asteroid::asteroid(AsteroidSize size,Vector2 pos) : size(size) {
    InitBySize();

    position = pos;
    // Random direction toward center
    float angle = ((rand() % 360) * M_PI / 180.0f);
    float speed = 50.0f + rand() % 100;
    velocity.setX(cos(angle) * speed);
    velocity.setY(sin(angle) * speed);

    rotationSpeed = 20.0f + rand() % 60;
}
//migth refactor
void asteroid::InitBySize() {
    switch (size) {
        case LARGE:
            points = 20;
            radius = 64;
            break;
        case MEDIUM:
            points = 30;
            radius = 32;
            break;
        case SMALL:
            points = 50;
            radius = 16;
            break;
    }
}
Vector2 asteroid::RandomEdgeSpawn() {
    //hardcoded
    int screenW = 1000;
    int screenH = 1000;
    int side = rand() % 4;

    switch (side) {
        case 0: return { (float)(rand() % screenW), 0.0f };           
        case 1: return { (float)(rand() % screenW), (float)screenH }; 
        case 2: return { 0.0f, (float)(rand() % screenH) };           
        default: return { (float)screenW, (float)(rand() % screenH) };
    }
}

void asteroid::Update(float delta) {
    position.setX(position.getX() + velocity.getX() * delta);
    position.setY(position.getY() + velocity.getY() * delta);

    rotationAngle += rotationSpeed * delta;
    if (rotationAngle > 360) rotationAngle -= 360.0f;

    //bounds
    if (position.getX() < -radius)  position.setX(1000 + radius);
    if (position.getX() > 1000 + radius) position.setX(-radius);
    if (position.getY() < -radius)  position.setY(1000 + radius);
    if (position.getY() > 1000 + radius) position.setY(-radius);
}

void asteroid::Render() {

    
    SDL_SetRenderDrawColor(GAME.GetRenderer(), 180, 180, 180, 255);

    float x = position.getX();
    float y = position.getY();


    //rendering generated by ai while im not using assets
    int segments = 20;
    for (int i = 0; i < segments; i++) {
        float a1 = (i / (float)segments) * 2 * M_PI;
        float a2 = ((i + 1) / (float)segments) * 2 * M_PI;
        SDL_RenderDrawLine(GAME.GetRenderer(),
            x + cos(a1) * radius,
            y + sin(a1) * radius,
            x + cos(a2) * radius,
            y + sin(a2) * radius
        );
    }
}

void asteroid::Hit(){



}

asteroid::~asteroid(){
    


}
